### ISSUE TITLE
No placing a bottom order 

### ISSUE THREAD

**Issue by Kossie72** [redlon23/HFTGrid#1]
Hi.
When starting the bot it creates all the grid orders, but when then the bot hits the order going up it is not create the bottom order. this creates a gap in the grid order as shown in the attachment. 
![Capture 7](https://user-images.githubusercontent.com/77004908/103646483-6aac5400-4f62-11eb-9893-abf6dac519b7.PNG)
![Capture 9](https://user-images.githubusercontent.com/77004908/103646523-7a2b9d00-4f62-11eb-977a-eced940dd258.png)

I have restarted

**Comment by redlon23** [comment]
The issue has been solved support through discord channel!
